# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  # researchuisource:
  #   image: researchuisource
  #   build:
  #     context: ./fe/research-ui
  #     dockerfile: Dockerfile    
  #   ports:
  #     - 4200:4200
    
  graphservice:
    container_name: "graph"
    image: graph
    build:
      context: ./svc/external
      dockerfile: info.sarins.services.knowledge/Dockerfile
    depends_on:
      - ne04jservice

    ports:
      - 8082:80
      - 8444:443

  vaultservice:
    container_name: "vault"
    image: vault
    build:
      context: ./svc/external
      dockerfile: info.sarins.services.vault/Dockerfile
    depends_on:
      - postgreservice
    ports:
      - 8081:80
      - 8443:443

  keycloakservice:
    container_name: "keycloak"
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

  ne04jservice:
    container_name: neo4j
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/P@ssw0rd
    volumes:
      - ./.neo4j/data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    
  postgreservice:
    container_name: postgresql
    image: postgres
    ports:
    - 5432:5432
    environment:
      - POSTGRES_DB=amlvaultdb
      - POSTGRES_USER=amluser
      - POSTGRES_PASSWORD=P@ssw0rd
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
  